// Generated by CoffeeScript 2.7.0
(function() {
  var name, person, yell;

  name = 'Scott';

  person = true;

  yell = function(name) {
    return console.log('Hello, ' + name + '!');
  };

  yell('blue');

}).call(this);
