// Generated by CoffeeScript 2.7.0
(function() {
  var eat, name, person, yell;

  name = 'Scott';

  person = true;

  yell = function(name) {
    return console.log('Hello, ' + name + '!');
  };

  yell('blue');

  yell('red');

  eat = function() {
    return console.log('I am eating');
  };

  eat();

}).call(this);
